# Generated by Django 5.1.3 on 2024-12-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='MembersData',
        ),
    ]
